### PR TITLE
refactor: move db initialize to tau_app container

### LINKED ISSUE #46: Move django postgres DB creation out of Postgres container first run, and into app container.
Currently, the first time the postgres container is spun up, an init script is run to generate both the Django DB, and the Django DB User.   If there is an error in the .env regarding the Django DB values during initial setup, this necessitates deleting the postgres volume before re-running the install process.

If we move the creation to a script that is run on the django/app container startup (where a script checks to see if the database/user exist, and if they dont, create them using the defined root `POSTGRES_PW`), these sorts of errors during setup are much easier to recover from- simply `docker compose down`, modify the values in the .env file, then `docker compose up`.

### PR DESCRIPTION
**Pull request by mtfoley**
@FiniteSingularity This PR is meant to fix #46 .  I needed to rework `wait_for_postgres.py` a bit.  I pruned out the old script and put this `wait_for_postgres.py` as the first command in the last Dockerfile step.  It should skip out if the DJANGO_DB_TYPE is not set to "postgres". I'm not sure if the formatted query strings are robust enough to best practice, but I'm definitely open to changes!

### CODE REVIEW

**Comment by mtfoley** [comment]
@FiniteSingularity updated per our conversation in discord:
- consolidated last command group in Dockerfile to new bash script
- update password for existing django user if found in Postgres. not checking for password match, as changing it again doesn't hurt...

**Comment by FiniteSingularity** [comment]
Made a couple of slight modifications:
1. Renamed the script from `start_django.sh` to `start.sh`
2. Fixed the paths from the script, to properly execute on startup.
3. Added proper +x permissions to `start.sh`

**Comment by mtfoley** [comment]
For whatever reasons those paths worked for me. As long as it runs :-)

**Comment by mtfoley** [comment]
'Twas being cached by docker. Your changes work after rebuild.

**Pull request merged**
